language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --env=prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  - cd dist
  - git push https://heroku:HEROKU_API_KEY@git.heroku.com/angular5demo.git master 
  

notifications:
  email:
    on_failure: change
    on_success: change