language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --env=prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  - git push https://heroku:d56fde01-a60a-4fb8-9317-aac6228a2499@git.heroku.com/angular5demo.git master 

notifications:
  email:
    on_failure: change
    on_success: change